 PREFIX strdf: <http://strdf.di.uoa.gr/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix time: <http://www.w3.org/2006/time#>
prefix gem: <http://za-geminat.cnrs.fr/Assolement.owl#>
PREFIX uom: <http://www.opengis.net/def/uom/OGC/1.0/>
select  ?name  (avg(?num) as ?avg)
 where
 {
 
   ?trap a gem:Trapset.
   ?trap gem:geometry ?geomt.
   ?nestobs a gem:NestObsv.
   ?nestobs gem:geometry ?geomn.
   filter(strdf:distance(?geomn, ?geomt, uom:metre)<="300"^^xsd:double)
   ?trap gem:hasTime ?t1.
   ?nestobs gem:hasTime ?t2.
   ?t1 time:inXSDDateTime ?dt1.
   bind(month(?dt1) as ?m1).
   bind(year(?dt1) as ?y1).
   ?t2 time:inXSDDateTime ?dt2.
   bind(month(?dt1) as ?m2).
   bind(year(?dt1) as ?y2).
   filter(?m1=?m2 && ?y1=?y2)
   ?trap gem:numOfIndv ?num.
   ?nestobs gem:isNestOf ?sp.
   ?sp gem:sname ?name.
 }
group by ?name
     
             