PREFIX strdf: <http://strdf.di.uoa.gr/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
prefix time: <http://www.w3.org/2006/time#>
prefix gem: <http://za-geminat.cnrs.fr/Assolement.owl#>
insert 
{
?tsa gem:hasIntegration ?tsb.
}
where
{
 ?tsa a gem:TimeSlice.
 ?tsa gem:hasTime ?intva.
 ?intva time:intervalMeets ?intvb.
  ?tsb gem:hasTime ?intvb.
 ?tsa gem:pgeometry ?geoma.
 ?tsb gem:pgeometry ?geomb.
 FILTER(strdf:area(?geoma)>0.00000001)
 FILTER(strdf:intersects(?geoma,?geomb))
FILTER(strdf:area(strdf:intersection(?geoma, ?geomb))/ strdf:area(?geoma)>0.98 && strdf:area(?geomb)>strdf:area(?geoma))
}
