prefix time: <http://www.w3.org/2006/time#>
prefix gem: <http://za-geminat.cnrs.fr/Assolement.owl#>
       insert 
       {
       ?ts1 gem:hasFiliation ?ts2.
       }
	
 	where
 	{
        ?p gem:hasTimeSlice ?ts1.
 	    ?p gem:hasTimeSlice ?ts2.
        ?ts1 gem:hasTime ?t1.
 	    ?ts2 gem:hasTime ?t2.
        ?t1 time:intervalMeets ?t2.     
 	}